name: Build

on:
  push:
    branches: [ main ]
    tags:
      - '*'

  workflow_dispatch:

env:
    FORCE_COLOR : 'true' # Force colors in console output

jobs:
  Ubuntu:
    name: Ubuntu - GCC ${{ matrix.gcc_version }}
    runs-on: ubuntu-22.04
    env:
      CC : gcc-${{ matrix.gcc_version }}
      CXX: g++-${{ matrix.gcc_version }}
      TERM: 'xterm-256color'

    strategy:
      fail-fast: false
      matrix:
        gcc_version: [9, 10, 11]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Bison/Flex
      run: |
        sudo apt update
        sudo apt install bison flex -y

    - name: Build
      run: |
        mkdir cmake-build
        cd ./cmake-build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DVERBOSE=OFF
        cmake --build . --config Release --clean-first

    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: C++ Compiler Ubuntu - GCC v${{ matrix.gcc_version }}
        path: ./cmake-build/CppCompiler

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install Python dependencies
      run: sudo pip install pyinstaller PyQt5

    - name: Build GUI
      run: pyinstaller --name CppCompiler_GUI --onefile --add-binary ./cmake-build/CppCompiler:. ./gui/main.py

    - name: Upload GUI Binary
      uses: actions/upload-artifact@v3
      with:
        name: C++ Compiler GUI Ubuntu - GCC v${{ matrix.gcc_version }}
        path: ./dist/CppCompiler_GUI

    - name: Rename Files
      run: |
          mv ./cmake-build/CppCompiler CppCompiler_linux_gcc_${{ matrix.gcc_version }}
          mv ./dist/CppCompiler_GUI CppCompiler_GUI_linux_gcc_${{ matrix.gcc_version }}


    - name: List Files
      if: always()
      run: ls -lRh

    - name: Release Files
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        name: "C++ Compiler v${{ github.event.release.tag_name }}"
        files: ./CppCompiler*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

########################################################################################

  Windows:
    name: Windows - ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - cmake_generator: CodeBlocks - MinGW Makefiles
            cmake_platform_args: " "
            name: Mingw-w64 GCC 8
            output_name: mingw64_gcc_8
            os: windows-latest
            
          - cmake_generator: Visual Studio 16 2019
            cmake_platform_args: -A x64
            name: Visual Studio 2019
            output_name: vs2019
            os: windows-2019
            
          - cmake_generator: Visual Studio 17 2022
            cmake_platform_args: -A x64
            name: Visual Studio 2022
            output_name: vs2022
            os: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Bison/Flex
      run: choco install winflexbison3

    - name: Build
      run: |
        mkdir cmake-build
        cd ./cmake-build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DVERBOSE=OFF -G "${{ matrix.cmake_generator }}" ${{ matrix.cmake_platform_args }}
        cmake --build . --config Release --clean-first

    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: C++ Compiler Windows x64 - ${{ matrix.name }}
        path: |
          # Path varies from Visual Studio to MinGW
          ./cmake-build/CppCompiler.exe
          ./cmake-build/*/CppCompiler.exe

    - name: Rename Files
      shell: bash
      run: mv ./cmake-build/CppCompiler.exe ./CppCompiler.exe || mv ./cmake-build/*/CppCompiler.exe ./CppCompiler.exe

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install Python dependencies
      run: pip install pyinstaller PyQt5

    - name: Build GUI
      run: pyinstaller --name CppCompiler_GUI --onefile --add-binary ./CppCompiler.exe;. ./gui/main.py

    - name: Upload GUI Binary
      uses: actions/upload-artifact@v3
      with:
        name: C++ Compiler GUI Ubuntu - GCC v${{ matrix.gcc_version }}
        path: ./dist/CppCompiler_GUI.exe

    - name: Rename Files
      shell: bash
      run: |
        mv CppCompiler.exe CppCompiler_win64_${{ matrix.output_name }}.exe
        mv ./dist/CppCompiler_GUI.exe CppCompiler_GUI_win64_${{ matrix.output_name }}.exe

    - name: List Files
      shell: bash
      run: ls -lRh

    - name: Release Files
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        name: "C++ Compiler v${{ github.event.release.tag_name }}"
        files: ./CppCompiler*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
